#!/bin/bash

# Script to clean LaTeX auxiliary files for arXiv submission

# Dr Jesús Rubio
# jesus@rubiojimenez.com

# Created: February 2024
# Last modified: June 2025

# Extensions to be deleted; add more as needed
delete_files() {
    local extension="$1"
    find . -type f -name "*.$extension" -exec rm -f {} +
}

EXTENSIONS="aux blg end log out toc" # assumes a pdflatex + bibtex workflow

for ext in $EXTENSIONS; do
    delete_files "$ext"
done

# Auxiliary files to be deleted; add more as needed
file=(*Notes.bib)
[ -f "${file[0]}" ] && rm "${file[0]}"